# nginx.conf
worker_processes  1;
events { worker_connections 1024; }

http {
    charset utf-8;                    # ← добавили

    upstream api { server api:8080; }

    server {
        listen 80;

        # Проксируем API под /api/
        location /api/ {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            rewrite ^/api/?(.*)$ /$1 break;
        }

        # Временная заглушка для фронта
        location / {
            add_header Content-Type "text/plain; charset=utf-8" always;   # ← ключевая строка
            return 200 "Gateway OK. Frontend подключится позже.";
        }
    }
}
